name: Publish Static Web App

on:
  push:
    branches:
    - master

jobs:
  build_and_publish:
    name: Build and Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        shell: bash
        run: |
          sudo npm install -g netlify-cli

      - name: Install npm packages
        shell: bash
        run: |
          npm install

      - name: Build app
        shell: bash
        run: |
          npm run build
      
      - name: Publish app
        shell: bash
        run: |
          netlify deploy --dir=public -p -s ${{ secrets.NETLIFY_SITE_ID }} -a ${{ secrets.NETLIFY_AUTH_TOKEN }}
