name: Pull Request

on:
  pull_request:
    branches:
    - master
    types:
    - opened

jobs:
  schedule_publish:
    name: Schedule Publish

    runs-on: ubuntu-latest

    steps:
    - name: Check PR body
      id: prbody
      shell: bash
      run: |
        echo ::set-output name=published::$(echo ${{ toJSON(github.event.pull_request.body) }})

    - name: Schedule publish
      shell: bash
      run: |
        curl -X POST 'https://${{ secrets.AZURE_FUNCTIONS_NAME }}.azurewebsites.net/api/orchestrators/schedule-event' \
        -d '{ "owner": "devkimchi", "repository": "live0507", "issueId": ${{ github.event.pull_request.number }}, "schedule": "${{ steps.prbody.outputs.published }}" }' \
        -H 'x-functions-key: ${{ secrets.AZURE_FUNCTIONS_KEY }}' \
        -H 'Content-Type: application/json'
